# Generated by Django 6.0.1 on 2026-02-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_allow_guest_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='erp_sales_invoice_name',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
