# Generated by Django 6.0.1 on 2026-02-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_erp_sales_invoice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='erp_sales_invoice_name',
        ),
    ]
